### ISSUE TITLE
Hello, I want to work with you to make a monogame editor

### ISSUE THREAD

**Issue by esengine** [BrettStory/Macabre2D#1]
I have an open source project that is just like you. Would you like to do this editor with me?

https://github.com/ClEngine/ClEngine

**Comment by esengine** [comment]
My ui editor hasn't started yet. I only have a rough idea. When I see your editor, I think, yes, I just need this ui editor. What you did was awesome. Although it was not yet complete, I saw its future.

**Comment by BrettStory** [comment]
Hey, sorry I'm not looking to work on any other engines. Macabre2D is just a fun hobby project I do on the side. You're more than welcome to use ideas and code that you find in my engine, though!

Thanks for your interest.

**Comment by esengine** [comment]
My friend, you understand my meaning. I want to edit an editor with you, and use your engine.
